# Generated by Django 5.1.4 on 2024-12-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurustudentassociation',
            name='students',
            field=models.ManyToManyField(related_name='students', to='backend.student'),
        ),
    ]
