# Generated by Django 5.0.6 on 2024-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_gurustudentassociation_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstudentregistration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='bulk_proofs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_studying',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='student_proofs/'),
        ),
    ]
